# Generated by Django 3.2.15 on 2022-09-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='imgae',
            new_name='image',
        ),
    ]
